sudo: required
language: c
compiler: gcc

arch:
  packages:
    - git
    - meson
    - vala
    - gtk3
  script:
    - mkdir build
    - meson build
    - ninja -C build
    - ninja -C build test

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
