sudo: required
language: c
compiler: gcc
arch:
  packages:
    -gtk3
    -xdg-utils
    -git
    -vala
    -autogen
    -libltdl
    -intltool
  script:
    - ./autogen.sh
    - make
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
