#!/bin/sh

if [ $(git branch | grep "*" | cut -c 3-) == "master" ]
then
	echo "Actualizando version en configure.ac"
	scripts/cambiar_version
	git add configure.ac

	echo "Actualizando POTFILES"
	cd po
	../scripts/crear-potfiles > /dev/null 2> /dev/null
	cd ..

	make -C po nomeolvides.pot
	msgmerge -U po/es.po po/nomeolvides.pot

	git add po/POTFILES.in
	git add po/POTFILES.skip
	git add po/nomeolvides.pot
	git add po/es.po
fi

